feat: 배포 스크립트 추기
CourseDesign/koa-boilerplate pull request #31
Opened 2021-03-18 13:20 UTC by 5d-jh

## 관련 이슈

## 현재 상황

## 개선 방법

## 예상 되는 부수 효과

## TODO
- [ ] 테스트 코드 작성
- [x] 비즈니스 로직 작성
- [x] 로컬 환경에서 테스트

## Reference

2021-03-19 03:10 UTC, siyual-park reviewed
저번에 레퍼런스로 드린 최적화 방법을 일어 보시면서 추가적인 최적화가 있으면 좋을거 같아요

2021-03-19 03:13 UTC, siyual-park commented on Dockerfile
> +
프로젝트 빌드 필요

2021-03-19 03:13 UTC, siyual-park commented on .github/workflows/deploy-production.yml
> +#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
STG 아 아니라 PRD로 번경

2021-03-19 03:13 UTC, siyual-park commented on .github/workflows/deploy-production.yml
> +#      - name: Build
빌드 과정이 되도록이면 dockerfile에 있으면 좋을거 같아요.

2021-03-19 03:15 UTC, siyual-park commented on .github/workflows/deploy-production.yml
> +#          application_name: foobar-project
어플리케이션 이름 환경 변수로 관리

2021-03-19 03:33 UTC, 5d-jh commented
혹시 링크 주실 수 있으신가요?

2021-03-19 03:36 UTC, 5d-jh commented on Dockerfile
> +
저도 컨테이너 내에서 빌드하는게 좋다고 생각했었는데 지금 상황에서는 밖에서 하는게 더 좋을 것 같습니다.

그 이유가 컨테이너 내에서 빌드하면 devDependencies까지 설치해야 되는 번거로움이 있고, 컨테이너 내에는 git이 설치되어있지 않아 husky 관련하여 오류가 발생하더라고요. 컨테이너를 최대한 가볍게 만드는게 좋을 것 같습니다.

2021-03-19 03:43 UTC, siyual-park commented
> 혹시 링크 주실 수 있으신가요?

파일 서버 이슈에 레퍼런스로 들어가 있어요

2021-03-19 04:54 UTC, siyual-park commented
https://github.com/CourseDesign/file-backend/issues/41

2021-03-23 00:25 UTC, siyual-park commented
@5d-jh 이거 develop 브런치 최신 반영하고 테스트 부탁드려요

2021-03-23 01:41 UTC, siyual-park commented on .dockerignore
> -
삭제 된것 확인 필요

2021-03-23 01:42 UTC, siyual-park requested changes
타겟 브런치가 master 로 되어 있었어요. 리뷰 단것 확인부탁드릴게요

2021-03-23 01:42 UTC, siyual-park commented on .github/workflows/deploy-production.yml
> +#      - name: Build
필요 한지?

2021-03-23 01:42 UTC, siyual-park commented on commons/util-types/lib/deserializable.ts
> +interface Deserializable<T> {
삭제

2021-03-23 01:42 UTC, siyual-park commented on commons/util-types/lib/serializable.ts
> +interface Serializable {
삭제

2021-03-23 01:42 UTC, siyual-park commented on commons/util-types/lib/static-implements.decorator.ts
> +function staticImplements<T>(): <U extends T>(constructor: U) => void {
삭제

2021-03-23 03:19 UTC, 5d-jh commented on .github/workflows/deploy-production.yml
> +#          application_name: foobar-project
각 job마다 환경 변수를 설정해줘야해서 크게 의미가 없을 것 같아요

2021-03-23 03:47 UTC, siyual-park approved these changes

2021-03-23 07:27 UTC, merged