feat: 도커파일 추가
CourseDesign/koa-boilerplate pull request #38
Opened 2021-03-20 07:10 UTC by 5d-jh

## 관련 이슈

## 현재 상황

## 개선 방법

## 예상 되는 부수 효과

## TODO
- [ ] 테스트 코드 작성
- [x] 비즈니스 로직 작성
- [x] 로컬 환경에서 테스트

## Reference

2021-03-20 07:13 UTC, siyual-park requested changes
빌드 과정이 안들어 간것 같아요

2021-03-20 07:15 UTC, 5d-jh commented
제가 어제 말했듯이 밖에서 빌드하면 devDependencies와 dependencies가 깔끔하게 분리되는점, 내부에서 빌드를 진행하면 husky hook 때문에 컨테이너 내부에 git을 설치해야 한다는 점 때문에 밖에서 빌드하도록 해둔 상태에요

2021-03-20 07:16 UTC, siyual-park commented
+ 도커 이그노얼
+ Multi-stage build 적용

2021-03-20 07:16 UTC, siyual-park commented
> 제가 어제 말했듯이 밖에서 빌드하면 devDependencies와 dependencies가 깔끔하게 분리되는점, 내부에서 빌드를 진행하면 husky hook 때문에 컨테이너 내부에 git을 설치해야 한다는 점 때문에 밖에서 빌드하도록 해둔 상태에요

저번에 말씀 드렸던 node docker optimise 에 들어 가시면 Multi-stage build 를 사용해서 최종 빌드를 가볍게 유지 하는 방법이 있어요 확인 부탁드려요
https://buddy.works/tutorials/optimizing-dockerfile-for-node-js-part-2

2021-03-20 07:23 UTC, 5d-jh commented
아 멀티스테이지 빌드가 있는줄은 몰랐네요 적용해 두겠습니다

2021-03-21 06:25 UTC, siyual-park commented on Dockerfile
> +RUN ["npm", "i", "--production", "--ignore-scripts"]
이 부분 명령어도 다른 stage로 빼면 좋을거 같아요. Run할때 마다 새로운 레이어가 생겨서 도커 파일 크기가 증가 해서요

2021-03-21 06:25 UTC, siyual-park commented on Dockerfile
> +WORKDIR /src/
src가 적절 한지..?

2021-03-21 06:35 UTC, 5d-jh commented on Dockerfile
> +WORKDIR /src/
linux root folder랑 헷갈릴 수도 있겠네요. coursedesign-app이 적당할까요?

2021-03-21 06:39 UTC, 5d-jh commented on Dockerfile
> +RUN ["npm", "i", "--production", "--ignore-scripts"]
그 부분은 같은 레이어에서 실행해야되는 부분이라 힘들지 않을까요?

2021-03-22 03:55 UTC, siyual-park commented on Dockerfile
> +WORKDIR /src/
app 이 좀더 적절할거 같아요

2021-03-22 03:56 UTC, siyual-park commented on Dockerfile
> +RUN ["npm", "i", "--production", "--ignore-scripts"]
build stage 에 있어도 되지 않을까? 하는 생각이 있어요

2021-03-22 03:59 UTC, siyual-park commented on Dockerfile
> +ENTRYPOINT ["pm2", "start", "applications/network/dist/index.js", "--no-daemon"]
pm2 는 도커가 아니라 실제 디펜던시로 추가 하고 config 파일을 이용해서 클러스터 모드로 동작 시키는것은 어떨까요

2021-03-22 04:01 UTC, siyual-park commented on Dockerfile
> +ENTRYPOINT ["pm2", "start", "applications/network/dist/index.js", "--no-daemon"]
음 일단 그냥 가는게 좀더 좋아 보이네요

2021-03-22 04:02 UTC, siyual-park approved these changes

2021-03-22 04:33 UTC, merged

2021-03-22 04:36 UTC, 5d-jh commented
@siyual-park 이거 스쿼시 머지가 안된것 같은데 revert 할까요..?

2021-03-22 05:01 UTC, siyual-park commented
revert도 로그는 그대로 남는걸로 알고 있어서 commit 전까지 head 옮기고 강제 push 날려주세요